"""empty message

Revision ID: 028cbab33c39
Revises: f81a0af2dd71
Create Date: 2020-04-19 13:07:35.616438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028cbab33c39'
down_revision = 'f81a0af2dd71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_models', sa.Column('last_predict_at', sa.DateTime(), nullable=True))
    op.add_column('train_models', sa.Column('qtd_predict', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('train_models', 'qtd_predict')
    op.drop_column('train_models', 'last_predict_at')
    # ### end Alembic commands ###
