"""empty message

Revision ID: 3352c2274787
Revises: 7475e181870f
Create Date: 2020-04-21 18:53:17.428445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3352c2274787'
down_revision = '7475e181870f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filename', sa.String(), nullable=False))
    op.drop_column('files', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('files', 'filename')
    # ### end Alembic commands ###
