"""empty message

Revision ID: 6144ba9b2330
Revises: daaf927bf9cd
Create Date: 2020-02-15 16:49:31.167820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6144ba9b2330'
down_revision = 'daaf927bf9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lms_name'), 'lms', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lms_name'), table_name='lms')
    # ### end Alembic commands ###
