"""empty message

Revision ID: 730d80dfb3f2
Revises: 7a111c4531fe
Create Date: 2020-03-03 20:16:14.794210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730d80dfb3f2'
down_revision = '7a111c4531fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moodle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso', sa.String(), nullable=False),
    sa.Column('semestre', sa.String(), nullable=False),
    sa.Column('período', sa.String(), nullable=False),
    sa.Column('nome_da_disciplina', sa.String(), nullable=False),
    sa.Column('id_da_disciplina', sa.String(), nullable=False),
    sa.Column('data_de_início', sa.String(), nullable=False),
    sa.Column('data_de_final', sa.String(), nullable=False),
    sa.Column('nome_do_aluno', sa.String(), nullable=False),
    sa.Column('id_do_aluno', sa.String(), nullable=False),
    sa.Column('var01', sa.Float(), nullable=False),
    sa.Column('var02', sa.Float(), nullable=False),
    sa.Column('var03', sa.Float(), nullable=False),
    sa.Column('var04', sa.Float(), nullable=False),
    sa.Column('var05', sa.Float(), nullable=False),
    sa.Column('var06', sa.Float(), nullable=False),
    sa.Column('var07', sa.Float(), nullable=False),
    sa.Column('var08', sa.Float(), nullable=False),
    sa.Column('var09', sa.Float(), nullable=False),
    sa.Column('var10', sa.Float(), nullable=False),
    sa.Column('var12', sa.Float(), nullable=False),
    sa.Column('var13', sa.Float(), nullable=False),
    sa.Column('var14', sa.Float(), nullable=False),
    sa.Column('var15', sa.Float(), nullable=False),
    sa.Column('var16', sa.Float(), nullable=False),
    sa.Column('var17', sa.Float(), nullable=False),
    sa.Column('var18', sa.Float(), nullable=False),
    sa.Column('var19', sa.Float(), nullable=False),
    sa.Column('var20', sa.Float(), nullable=False),
    sa.Column('var21', sa.Float(), nullable=False),
    sa.Column('var22', sa.Float(), nullable=False),
    sa.Column('var23', sa.Float(), nullable=False),
    sa.Column('var24', sa.Float(), nullable=False),
    sa.Column('var25', sa.Float(), nullable=False),
    sa.Column('var28', sa.Float(), nullable=False),
    sa.Column('var29', sa.Float(), nullable=False),
    sa.Column('var30', sa.Float(), nullable=False),
    sa.Column('var31', sa.Float(), nullable=False),
    sa.Column('var31b', sa.Float(), nullable=False),
    sa.Column('var31c', sa.Float(), nullable=False),
    sa.Column('var32a', sa.Float(), nullable=False),
    sa.Column('var32b', sa.Float(), nullable=False),
    sa.Column('var32c', sa.Float(), nullable=False),
    sa.Column('var32d', sa.Float(), nullable=False),
    sa.Column('var33', sa.Float(), nullable=False),
    sa.Column('var34', sa.Float(), nullable=False),
    sa.Column('var35', sa.Float(), nullable=False),
    sa.Column('prova01', sa.Float(), nullable=False),
    sa.Column('prova01_2chamada', sa.Float(), nullable=False),
    sa.Column('primeira_prova', sa.Float(), nullable=False),
    sa.Column('prova02', sa.Float(), nullable=False),
    sa.Column('prova02_2chamada', sa.Float(), nullable=False),
    sa.Column('segunda_prova', sa.Float(), nullable=False),
    sa.Column('media_provas', sa.Float(), nullable=False),
    sa.Column('forum01', sa.Float(), nullable=False),
    sa.Column('forum02', sa.Float(), nullable=False),
    sa.Column('forum03', sa.Float(), nullable=False),
    sa.Column('forum04', sa.Float(), nullable=False),
    sa.Column('media_forum', sa.Float(), nullable=False),
    sa.Column('webquest01', sa.Float(), nullable=False),
    sa.Column('webquest02', sa.Float(), nullable=False),
    sa.Column('media_webquest', sa.Float(), nullable=False),
    sa.Column('desempenho', sa.Float(), nullable=False),
    sa.Column('desempenho_binario', sa.Float(), nullable=False),
    sa.Column('desempenho_classes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moodle')
    # ### end Alembic commands ###
