"""empty message

Revision ID: 812eb5f121b8
Revises: 14553875c679
Create Date: 2020-04-18 19:19:49.632408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812eb5f121b8'
down_revision = '14553875c679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_models',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_models_model_id'), 'train_models', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_models_model_id'), table_name='train_models')
    op.drop_table('train_models')
    # ### end Alembic commands ###
